/*Copyright (c) 2018-2019 rubaya.io All Rights Reserved.
 This software is the confidential and proprietary information of rubaya.io You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with rubaya.io*/
package com.tax_projects.cmtaxprojects.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class DefaultdispatcherResponse implements Serializable {


    @ColumnAlias("id")
    private Integer id;

    @ColumnAlias("dispatcher")
    private String dispatcher;

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getDispatcher() {
        return this.dispatcher;
    }

    public void setDispatcher(String dispatcher) {
        this.dispatcher = dispatcher;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof DefaultdispatcherResponse)) return false;
        final DefaultdispatcherResponse defaultdispatcherResponse = (DefaultdispatcherResponse) o;
        return Objects.equals(getId(), defaultdispatcherResponse.getId()) &&
                Objects.equals(getDispatcher(), defaultdispatcherResponse.getDispatcher());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(),
                getDispatcher());
    }
}