/*Copyright (c) 2018-2019 rubaya.io All Rights Reserved.
 This software is the confidential and proprietary information of rubaya.io You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with rubaya.io*/
package com.tax_projects.cmtaxprojects.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class DefaultreviewerResponse implements Serializable {


    @ColumnAlias("id")
    private Integer id;

    @ColumnAlias("reviewer")
    private String reviewer;

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getReviewer() {
        return this.reviewer;
    }

    public void setReviewer(String reviewer) {
        this.reviewer = reviewer;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof DefaultreviewerResponse)) return false;
        final DefaultreviewerResponse defaultreviewerResponse = (DefaultreviewerResponse) o;
        return Objects.equals(getId(), defaultreviewerResponse.getId()) &&
                Objects.equals(getReviewer(), defaultreviewerResponse.getReviewer());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(),
                getReviewer());
    }
}