/*Copyright (c) 2018-2019 rubaya.io All Rights Reserved.
 This software is the confidential and proprietary information of rubaya.io You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with rubaya.io*/
package com.tax_projects.cmtaxprojects.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.sql.Date;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetCurrentDateResponse implements Serializable {


    @ColumnAlias("CURRENT_DATE")
    private Date currentDate;

    public Date getCurrentDate() {
        return this.currentDate;
    }

    public void setCurrentDate(Date currentDate) {
        this.currentDate = currentDate;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetCurrentDateResponse)) return false;
        final GetCurrentDateResponse getCurrentDateResponse = (GetCurrentDateResponse) o;
        return Objects.equals(getCurrentDate(), getCurrentDateResponse.getCurrentDate());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getCurrentDate());
    }
}