/*Copyright (c) 2018-2019 rubaya.io All Rights Reserved.
 This software is the confidential and proprietary information of rubaya.io You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with rubaya.io*/
package com.tax_projects.cmtaxprojects.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetProjectIdResponse implements Serializable {


    @ColumnAlias("max(id)")
    private Integer max_id_;

    public Integer getMax_id_() {
        return this.max_id_;
    }

    public void setMax_id_(Integer max_id_) {
        this.max_id_ = max_id_;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetProjectIdResponse)) return false;
        final GetProjectIdResponse getProjectIdResponse = (GetProjectIdResponse) o;
        return Objects.equals(getMax_id_(), getProjectIdResponse.getMax_id_());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getMax_id_());
    }
}