/*Copyright (c) 2018-2019 rubaya.io All Rights Reserved.
 This software is the confidential and proprietary information of rubaya.io You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with rubaya.io*/
package com.tax_projects.cmtaxprojects.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class PartnersListResponse implements Serializable {


    @ColumnAlias("id")
    private Integer id;

    @ColumnAlias("username")
    private String username;

    @ColumnAlias("firstname")
    private String firstname;

    @ColumnAlias("lastname")
    private String lastname;

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getFirstname() {
        return this.firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    public String getLastname() {
        return this.lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof PartnersListResponse)) return false;
        final PartnersListResponse partnersListResponse = (PartnersListResponse) o;
        return Objects.equals(getId(), partnersListResponse.getId()) &&
                Objects.equals(getUsername(), partnersListResponse.getUsername()) &&
                Objects.equals(getFirstname(), partnersListResponse.getFirstname()) &&
                Objects.equals(getLastname(), partnersListResponse.getLastname());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(),
                getUsername(),
                getFirstname(),
                getLastname());
    }
}