/*Copyright (c) 2018-2019 rubaya.io All Rights Reserved.
 This software is the confidential and proprietary information of rubaya.io You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with rubaya.io*/
package com.tax_projects.cmtaxprojects.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class PreparersListResponse implements Serializable {


    @ColumnAlias("id")
    private Integer id;

    @ColumnAlias("username")
    private String username;

    @ColumnAlias("empname")
    private String empname;

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getEmpname() {
        return this.empname;
    }

    public void setEmpname(String empname) {
        this.empname = empname;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof PreparersListResponse)) return false;
        final PreparersListResponse preparersListResponse = (PreparersListResponse) o;
        return Objects.equals(getId(), preparersListResponse.getId()) &&
                Objects.equals(getUsername(), preparersListResponse.getUsername()) &&
                Objects.equals(getEmpname(), preparersListResponse.getEmpname());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(),
                getUsername(),
                getEmpname());
    }
}