/*Copyright (c) 2018-2019 rubaya.io All Rights Reserved.
 This software is the confidential and proprietary information of rubaya.io You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with rubaya.io*/
package com.tax_projects.cmtaxprojects.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class TaxyearResponse implements Serializable {


    @ColumnAlias("taxyear")
    private Long taxyear;

    public Long getTaxyear() {
        return this.taxyear;
    }

    public void setTaxyear(Long taxyear) {
        this.taxyear = taxyear;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof TaxyearResponse)) return false;
        final TaxyearResponse taxyearResponse = (TaxyearResponse) o;
        return Objects.equals(getTaxyear(), taxyearResponse.getTaxyear());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getTaxyear());
    }
}