/*Copyright (c) 2018-2019 rubaya.io All Rights Reserved.
 This software is the confidential and proprietary information of rubaya.io You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with rubaya.io*/
package com.tax_projects.cmtaxprojects.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class TestResponse implements Serializable {


    @ColumnAlias("userid")
    private Integer userid;

    @ColumnAlias("notifyid")
    private Integer notifyid;

    @ColumnAlias("projectid")
    private Integer projectid;

    @ColumnAlias("personid")
    private Integer personid;

    public Integer getUserid() {
        return this.userid;
    }

    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    public Integer getNotifyid() {
        return this.notifyid;
    }

    public void setNotifyid(Integer notifyid) {
        this.notifyid = notifyid;
    }

    public Integer getProjectid() {
        return this.projectid;
    }

    public void setProjectid(Integer projectid) {
        this.projectid = projectid;
    }

    public Integer getPersonid() {
        return this.personid;
    }

    public void setPersonid(Integer personid) {
        this.personid = personid;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof TestResponse)) return false;
        final TestResponse testResponse = (TestResponse) o;
        return Objects.equals(getUserid(), testResponse.getUserid()) &&
                Objects.equals(getNotifyid(), testResponse.getNotifyid()) &&
                Objects.equals(getProjectid(), testResponse.getProjectid()) &&
                Objects.equals(getPersonid(), testResponse.getPersonid());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getUserid(),
                getNotifyid(),
                getProjectid(),
                getPersonid());
    }
}