/*Copyright (c) 2018-2019 rubaya.io All Rights Reserved.
 This software is the confidential and proprietary information of rubaya.io You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with rubaya.io*/
package com.tax_projects.cmtaxprojects.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class UsersListResponse implements Serializable {


    @ColumnAlias("id")
    private Integer id;

    @ColumnAlias("user")
    private String user;

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getUser() {
        return this.user;
    }

    public void setUser(String user) {
        this.user = user;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof UsersListResponse)) return false;
        final UsersListResponse usersListResponse = (UsersListResponse) o;
        return Objects.equals(getId(), usersListResponse.getId()) &&
                Objects.equals(getUser(), usersListResponse.getUser());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(),
                getUser());
    }
}