/*Copyright (c) 2018-2019 rubaya.io All Rights Reserved.
 This software is the confidential and proprietary information of rubaya.io You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with rubaya.io*/
package com.tax_projects.cmtaxprojects.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class UsformsResponse implements Serializable {


    @ColumnAlias("id")
    private Integer id;

    @ColumnAlias("usforms")
    private String usforms;

    @ColumnAlias("canadian")
    private String canadian;

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getUsforms() {
        return this.usforms;
    }

    public void setUsforms(String usforms) {
        this.usforms = usforms;
    }

    public String getCanadian() {
        return this.canadian;
    }

    public void setCanadian(String canadian) {
        this.canadian = canadian;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof UsformsResponse)) return false;
        final UsformsResponse usformsResponse = (UsformsResponse) o;
        return Objects.equals(getId(), usformsResponse.getId()) &&
                Objects.equals(getUsforms(), usformsResponse.getUsforms()) &&
                Objects.equals(getCanadian(), usformsResponse.getCanadian());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(),
                getUsforms(),
                getCanadian());
    }
}