/*Copyright (c) 2018-2019 rubaya.io All Rights Reserved.
 This software is the confidential and proprietary information of rubaya.io You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with rubaya.io*/
package com.tax_projects.cmtaxprojects;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Offices generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`offices`")
public class Offices implements Serializable {

    private Integer id;
    private String officename;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`ID`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "`officename`", nullable = true, length = 255)
    public String getOfficename() {
        return this.officename;
    }

    public void setOfficename(String officename) {
        this.officename = officename;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Offices)) return false;
        final Offices offices = (Offices) o;
        return Objects.equals(getId(), offices.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}