/*Copyright (c) 2018-2019 rubaya.io All Rights Reserved.
 This software is the confidential and proprietary information of rubaya.io You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with rubaya.io*/
package com.tax_projects.cmtaxprojects;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.sql.Date;
import java.sql.Timestamp;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.ForeignKey;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * Projects generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`projects`")
public class Projects implements Serializable {

    private Integer id;
    private Integer clientid;
    private Integer partnerid;
    private Integer preparerid;
    private Integer reviewerid;
    private Integer dispatcherid;
    private Integer officeid;
    private Integer statusid;
    private Date receiveddate;
    private Date prepareddate;
    private Date revieweddate;
    private Date efileformreceived;
    private Date completeddate;
    private String description;
    private String comments;
    private String _1040;
    private String _3520;
    private String _3520a;
    private String fbar;
    private String t1;
    private String statereturn;
    private String efileeligible;
    private Date _1040exdate;
    private Date _3520exdate;
    private Date _3520aexdate;
    private Date stateexdate;
    private String lastupdatedby;
    private Timestamp lastupdated;
    private Integer currentuser;
    private String billed;
    private Double fees;
    private Users usersByPreparerid;
    private Offices offices;
    private Users usersByPartnerid;
    private Users usersByDispatcherid;
    private Clients clients;
    private Users usersByReviewerid;
    private Workstatus workstatus;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`ID`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "`clientid`", nullable = true, scale = 0, precision = 10)
    public Integer getClientid() {
        return this.clientid;
    }

    public void setClientid(Integer clientid) {
        this.clientid = clientid;
    }

    @Column(name = "`partnerid`", nullable = true, scale = 0, precision = 10)
    public Integer getPartnerid() {
        return this.partnerid;
    }

    public void setPartnerid(Integer partnerid) {
        this.partnerid = partnerid;
    }

    @Column(name = "`preparerid`", nullable = true, scale = 0, precision = 10)
    public Integer getPreparerid() {
        return this.preparerid;
    }

    public void setPreparerid(Integer preparerid) {
        this.preparerid = preparerid;
    }

    @Column(name = "`reviewerid`", nullable = true, scale = 0, precision = 10)
    public Integer getReviewerid() {
        return this.reviewerid;
    }

    public void setReviewerid(Integer reviewerid) {
        this.reviewerid = reviewerid;
    }

    @Column(name = "`dispatcherid`", nullable = true, scale = 0, precision = 10)
    public Integer getDispatcherid() {
        return this.dispatcherid;
    }

    public void setDispatcherid(Integer dispatcherid) {
        this.dispatcherid = dispatcherid;
    }

    @Column(name = "`officeid`", nullable = true, scale = 0, precision = 10)
    public Integer getOfficeid() {
        return this.officeid;
    }

    public void setOfficeid(Integer officeid) {
        this.officeid = officeid;
    }

    @Column(name = "`statusid`", nullable = true, scale = 0, precision = 10)
    public Integer getStatusid() {
        return this.statusid;
    }

    public void setStatusid(Integer statusid) {
        this.statusid = statusid;
    }

    @Column(name = "`receiveddate`", nullable = true)
    public Date getReceiveddate() {
        return this.receiveddate;
    }

    public void setReceiveddate(Date receiveddate) {
        this.receiveddate = receiveddate;
    }

    @Column(name = "`prepareddate`", nullable = true)
    public Date getPrepareddate() {
        return this.prepareddate;
    }

    public void setPrepareddate(Date prepareddate) {
        this.prepareddate = prepareddate;
    }

    @Column(name = "`revieweddate`", nullable = true)
    public Date getRevieweddate() {
        return this.revieweddate;
    }

    public void setRevieweddate(Date revieweddate) {
        this.revieweddate = revieweddate;
    }

    @Column(name = "`efileformreceived`", nullable = true)
    public Date getEfileformreceived() {
        return this.efileformreceived;
    }

    public void setEfileformreceived(Date efileformreceived) {
        this.efileformreceived = efileformreceived;
    }

    @Column(name = "`completeddate`", nullable = true)
    public Date getCompleteddate() {
        return this.completeddate;
    }

    public void setCompleteddate(Date completeddate) {
        this.completeddate = completeddate;
    }

    @Column(name = "`description`", nullable = true, length = 255)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "`comments`", nullable = true, length = 255)
    public String getComments() {
        return this.comments;
    }

    public void setComments(String comments) {
        this.comments = comments;
    }

    @Column(name = "`1040`", nullable = true, length = 20)
    public String get_1040() {
        return this._1040;
    }

    public void set_1040(String _1040) {
        this._1040 = _1040;
    }

    @Column(name = "`3520`", nullable = true, length = 20)
    public String get_3520() {
        return this._3520;
    }

    public void set_3520(String _3520) {
        this._3520 = _3520;
    }

    @Column(name = "`3520a`", nullable = true, length = 20)
    public String get_3520a() {
        return this._3520a;
    }

    public void set_3520a(String _3520a) {
        this._3520a = _3520a;
    }

    @Column(name = "`fbar`", nullable = true, length = 20)
    public String getFbar() {
        return this.fbar;
    }

    public void setFbar(String fbar) {
        this.fbar = fbar;
    }

    @Column(name = "`t1`", nullable = true, length = 20)
    public String getT1() {
        return this.t1;
    }

    public void setT1(String t1) {
        this.t1 = t1;
    }

    @Column(name = "`statereturn`", nullable = true, length = 255)
    public String getStatereturn() {
        return this.statereturn;
    }

    public void setStatereturn(String statereturn) {
        this.statereturn = statereturn;
    }

    @Column(name = "`efileeligible`", nullable = true, length = 10)
    public String getEfileeligible() {
        return this.efileeligible;
    }

    public void setEfileeligible(String efileeligible) {
        this.efileeligible = efileeligible;
    }

    @Column(name = "`1040exdate`", nullable = true)
    public Date get_1040exdate() {
        return this._1040exdate;
    }

    public void set_1040exdate(Date _1040exdate) {
        this._1040exdate = _1040exdate;
    }

    @Column(name = "`3520exdate`", nullable = true)
    public Date get_3520exdate() {
        return this._3520exdate;
    }

    public void set_3520exdate(Date _3520exdate) {
        this._3520exdate = _3520exdate;
    }

    @Column(name = "`3520aexdate`", nullable = true)
    public Date get_3520aexdate() {
        return this._3520aexdate;
    }

    public void set_3520aexdate(Date _3520aexdate) {
        this._3520aexdate = _3520aexdate;
    }

    @Column(name = "`stateexdate`", nullable = true)
    public Date getStateexdate() {
        return this.stateexdate;
    }

    public void setStateexdate(Date stateexdate) {
        this.stateexdate = stateexdate;
    }

    @Column(name = "`lastupdatedby`", nullable = true, length = 255)
    public String getLastupdatedby() {
        return this.lastupdatedby;
    }

    public void setLastupdatedby(String lastupdatedby) {
        this.lastupdatedby = lastupdatedby;
    }

    @Column(name = "`lastupdated`", nullable = true)
    public Timestamp getLastupdated() {
        return this.lastupdated;
    }

    public void setLastupdated(Timestamp lastupdated) {
        this.lastupdated = lastupdated;
    }

    @Column(name = "`currentuser`", nullable = true, scale = 0, precision = 10)
    public Integer getCurrentuser() {
        return this.currentuser;
    }

    public void setCurrentuser(Integer currentuser) {
        this.currentuser = currentuser;
    }

    @Column(name = "`billed`", nullable = true, length = 10)
    public String getBilled() {
        return this.billed;
    }

    public void setBilled(String billed) {
        this.billed = billed;
    }

    @Column(name = "`fees`", nullable = true, scale = 2, precision = 10)
    public Double getFees() {
        return this.fees;
    }

    public void setFees(Double fees) {
        this.fees = fees;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`preparerid`", referencedColumnName = "`ID`", insertable = false, updatable = false, foreignKey = @ForeignKey(name = "`FK_users_TO_projects_ID_VZDUm`"))
    @Fetch(FetchMode.JOIN)
    public Users getUsersByPreparerid() {
        return this.usersByPreparerid;
    }

    public void setUsersByPreparerid(Users usersByPreparerid) {
        if(usersByPreparerid != null) {
            this.preparerid = usersByPreparerid.getId();
        }

        this.usersByPreparerid = usersByPreparerid;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`officeid`", referencedColumnName = "`ID`", insertable = false, updatable = false, foreignKey = @ForeignKey(name = "`FK_offices_TO_projects_IJdZtj`"))
    @Fetch(FetchMode.JOIN)
    public Offices getOffices() {
        return this.offices;
    }

    public void setOffices(Offices offices) {
        if(offices != null) {
            this.officeid = offices.getId();
        }

        this.offices = offices;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`partnerid`", referencedColumnName = "`ID`", insertable = false, updatable = false, foreignKey = @ForeignKey(name = "`FK_users_TO_projects_ID_FWtNv`"))
    @Fetch(FetchMode.JOIN)
    public Users getUsersByPartnerid() {
        return this.usersByPartnerid;
    }

    public void setUsersByPartnerid(Users usersByPartnerid) {
        if(usersByPartnerid != null) {
            this.partnerid = usersByPartnerid.getId();
        }

        this.usersByPartnerid = usersByPartnerid;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`dispatcherid`", referencedColumnName = "`ID`", insertable = false, updatable = false, foreignKey = @ForeignKey(name = "`FK_users_TO_projects_ID_0cZQm`"))
    @Fetch(FetchMode.JOIN)
    public Users getUsersByDispatcherid() {
        return this.usersByDispatcherid;
    }

    public void setUsersByDispatcherid(Users usersByDispatcherid) {
        if(usersByDispatcherid != null) {
            this.dispatcherid = usersByDispatcherid.getId();
        }

        this.usersByDispatcherid = usersByDispatcherid;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`clientid`", referencedColumnName = "`ID`", insertable = false, updatable = false, foreignKey = @ForeignKey(name = "`FK_clients_TO_projects_ItIrax`"))
    @Fetch(FetchMode.JOIN)
    public Clients getClients() {
        return this.clients;
    }

    public void setClients(Clients clients) {
        if(clients != null) {
            this.clientid = clients.getId();
        }

        this.clients = clients;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`reviewerid`", referencedColumnName = "`ID`", insertable = false, updatable = false, foreignKey = @ForeignKey(name = "`FK_users_TO_projects_ID_mp0Jf`"))
    @Fetch(FetchMode.JOIN)
    public Users getUsersByReviewerid() {
        return this.usersByReviewerid;
    }

    public void setUsersByReviewerid(Users usersByReviewerid) {
        if(usersByReviewerid != null) {
            this.reviewerid = usersByReviewerid.getId();
        }

        this.usersByReviewerid = usersByReviewerid;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`statusid`", referencedColumnName = "`ID`", insertable = false, updatable = false, foreignKey = @ForeignKey(name = "`FK_workstatus_TO_projectmDBNy`"))
    @Fetch(FetchMode.JOIN)
    public Workstatus getWorkstatus() {
        return this.workstatus;
    }

    public void setWorkstatus(Workstatus workstatus) {
        if(workstatus != null) {
            this.statusid = workstatus.getId();
        }

        this.workstatus = workstatus;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Projects)) return false;
        final Projects projects = (Projects) o;
        return Objects.equals(getId(), projects.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}