/*Copyright (c) 2018-2019 rubaya.io All Rights Reserved.
 This software is the confidential and proprietary information of rubaya.io You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with rubaya.io*/
package com.tax_projects.cmtaxprojects;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

public class WorkflowlogId implements Serializable {

    private Integer clientid;
    private Integer statusid;
    private Integer notifyid;
    private Integer projectid;

    public Integer getClientid() {
        return this.clientid;
    }

    public void setClientid(Integer clientid) {
        this.clientid = clientid;
    }

    public Integer getStatusid() {
        return this.statusid;
    }

    public void setStatusid(Integer statusid) {
        this.statusid = statusid;
    }

    public Integer getNotifyid() {
        return this.notifyid;
    }

    public void setNotifyid(Integer notifyid) {
        this.notifyid = notifyid;
    }

    public Integer getProjectid() {
        return this.projectid;
    }

    public void setProjectid(Integer projectid) {
        this.projectid = projectid;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Workflowlog)) return false;
        final Workflowlog workflowlog = (Workflowlog) o;
        return Objects.equals(getClientid(), workflowlog.getClientid()) &&
                Objects.equals(getStatusid(), workflowlog.getStatusid()) &&
                Objects.equals(getNotifyid(), workflowlog.getNotifyid()) &&
                Objects.equals(getProjectid(), workflowlog.getProjectid());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getClientid(),
                getStatusid(),
                getNotifyid(),
                getProjectid());
    }
}